### ISSUE TITLE
SPI_slave接收数组recvbuf始终为空

### ISSUE THREAD

**Issue by Adolf-K** [MihaiLupoiu/esp32_spi_slave#1]
你好，我在调试esp32的spi_slave过程中,我用stm32作为主机，esp32作为从机，两个STM32之间的SPI通信我已经测试过了，没有问题，但是在esp32当中我的接收数组recvbuf始终为空，但是通过打印t.trans_len显示我的已经接收到8位的数据，recvbuf也在DMA当中申请了内存，请教您这个问题您有没有遇到过，感谢
![image](https://user-images.githubusercontent.com/33571452/88539782-735c3e00-d044-11ea-99d0-e2a509a41966.png)

**Comment by MihaiLupoiu** [comment]
Unfortunately with that information it is not enough to tell what can be the problem. 

My guess is that could be related to configuration of the SPI. You should check that the speed that you are using in the SPI in between the STM32 and the ESP32 are the same. I would suggest you start with low speed and then increase it.
Also an important remark is that depending on the ESP32 pins that you are using you may not be able to use the full speed of the SPI. 

When I was testing it I was using the ESP IDF v3.2.3, check your IDF version in case there are problems with it regarding SPI.

Hope it helps! 🙂
